version: "3.3"

services:
  olx_back:
    container_name: olx_back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    networks:
      - olx_net
    depends_on:
      - olx_mongo
    env_file:
      - .env
    restart: always
    environment:
      MONGODB_URI: "mongodb://${DB_UNAME}:${DB_PWD}@olx_mongo:27017/${DB_NAME}"
    volumes:
      - ./backend:/usr/src/app
    command: ["node", "app.js"]

  olx_mongo:
    image: mongo:latest
    container_name: olx_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_UNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}

    ports:
      - 27018:27017
    networks:
      - olx_net
    volumes:
      - ./mongodb_data:/data/db

volumes:
  olxcoin:
  mongodb_data:

networks:
  olx_net:
    driver: bridge
