# Dockerfile.client

# Use official Node.js image as a base
FROM --platform=linux/amd64 node:20.12.1

WORKDIR /usr/src/app
# Copy package.json and package-lock.json files
COPY package*.json /usr/src/app
RUN ls -la
# Install dependencies
RUN npm install

RUN ls -la

# Copy all files
COPY . .
