# Dockerfile.client

# Use official Node.js image as a base
FROM node:20.12.1

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

WORKDIR /usr/src/app/

# Expose port (if necessary)
# EXPOSE 8080

# Command to run the application
# CMD ["npm", "run", "dev"]
